import { BarChart3 } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { CacheSeed } from "@/components/cache-seed";
import { assertRole, getSessionProfile } from "@/lib/auth";
import { cacheKeys } from "@/lib/cache-keys";
import type { MonthlyReport, RequestStatus } from "@/lib/types";

type ReportRequestRow = {
  id: string;
  employee_id: string;
  status: RequestStatus;
  quantity: number;
  created_at: string;
  inventory: { item_name: string; category: string } | null;
  employee: { full_name: string } | null;
};

export default async function ReportPage() {
  const { supabase, profile } = await getSessionProfile();
  assertRole(profile, ["manager", "admin"]);
  const endpoint = `${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/generate-monthly-report`;
  let report: MonthlyReport | null = null;
  let error: string | null = null;

  const {
    data: { session }
  } = await supabase.auth.getSession();

  if (session?.access_token && process.env.NEXT_PUBLIC_SUPABASE_URL) {
    try {
      const response = await fetch(endpoint, {
        headers: { Authorization: `Bearer ${session.access_token}` },
        cache: "no-store"
      });
      if (response.ok) {
        report = (await response.json()) as MonthlyReport;
      } else {
        error = await response.text();
      }
    } catch (requestError) {
      error = requestError instanceof Error ? requestError.message : "Report request failed.";
    }
  }

  if (!report) {
    const fallback = await generateReportFromDatabase(supabase);
    report = fallback.report;
    error = fallback.error;
  }

  return (
    <AppShell profile={profile}>
      {report ? <CacheSeed cacheKey={cacheKeys.monthlyReport} value={report} ttlMs={5 * 60 * 1000} /> : null}
      <div className="grid gap-6">
        <section>
          <h2 className="text-2xl font-black text-ink">Monthly report</h2>
          <p className="mt-1 text-steel">Generated by the Supabase Edge Function with JWT role validation.</p>
        </section>
        {report ? (
          <>
            <section className="grid gap-4 md:grid-cols-3">
              <ReportMetric label="Pending" value={report.totals.pending} />
              <ReportMetric label="Approved" value={report.totals.approved} />
              <ReportMetric label="Rejected" value={report.totals.rejected} />
            </section>
            <section className="panel overflow-hidden">
              <div className="border-b border-line p-4">
                <h3 className="font-bold text-ink">Category summary</h3>
              </div>
              <div className="overflow-x-auto">
                <table className="w-full min-w-[680px] text-left text-sm">
                  <thead className="bg-cloud text-xs uppercase text-steel">
                    <tr>
                      <th className="px-4 py-3">Category</th>
                      <th className="px-4 py-3">Pending</th>
                      <th className="px-4 py-3">Approved</th>
                      <th className="px-4 py-3">Rejected</th>
                      <th className="px-4 py-3">Total</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-line">
                    {report.by_category.map((row) => (
                      <tr key={row.category}>
                        <td className="px-4 py-3 font-semibold">{row.category}</td>
                        <td className="px-4 py-3">{row.pending}</td>
                        <td className="px-4 py-3">{row.approved}</td>
                        <td className="px-4 py-3">{row.rejected}</td>
                        <td className="px-4 py-3">{row.total}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </section>
          </>
        ) : (
          <div className="panel p-5">
            <BarChart3 className="mb-3 size-8 text-brand" />
            <p className="font-semibold text-ink">Report unavailable.</p>
            <p className="mt-2 text-sm text-steel">{error ?? "Report endpoint is not configured yet."}</p>
          </div>
        )}
      </div>
    </AppShell>
  );
}

async function generateReportFromDatabase(
  supabase: Awaited<ReturnType<typeof getSessionProfile>>["supabase"]
): Promise<{ report: MonthlyReport | null; error: string | null }> {
  const toDate = new Date();
  const fromDate = new Date(toDate);
  fromDate.setDate(toDate.getDate() - 30);

  const { data, error } = await supabase
    .from("requests")
    .select(
      "id, employee_id, status, quantity, created_at, inventory(item_name, category), employee:profiles!requests_employee_id_fkey(full_name)"
    )
    .gte("created_at", fromDate.toISOString())
    .lte("created_at", toDate.toISOString())
    .order("created_at", { ascending: false })
    .returns<ReportRequestRow[]>();

  if (error) {
    return { report: null, error: error.message };
  }

  const totals: Record<RequestStatus, number> = {
    pending: 0,
    approved: 0,
    rejected: 0
  };
  const byCategory = new Map<
    string,
    { category: string; pending: number; approved: number; rejected: number; total: number }
  >();

  for (const row of data ?? []) {
    totals[row.status] += 1;
    const category = row.inventory?.category ?? "Uncategorized";
    const current = byCategory.get(category) ?? {
      category,
      pending: 0,
      approved: 0,
      rejected: 0,
      total: 0
    };
    current[row.status] += 1;
    current.total += 1;
    byCategory.set(category, current);
  }

  return {
    report: {
      generated_at: toDate.toISOString(),
      from_date: fromDate.toISOString(),
      to_date: toDate.toISOString(),
      totals,
      by_category: [...byCategory.values()].sort((a, b) => b.total - a.total),
      recent_requests: (data ?? []).slice(0, 20).map((row) => ({
        id: row.id,
        employee_name: row.employee?.full_name ?? row.employee_id,
        item_name: row.inventory?.item_name ?? "Deleted item",
        category: row.inventory?.category ?? "Uncategorized",
        status: row.status,
        quantity: row.quantity,
        created_at: row.created_at
      }))
    },
    error: null
  };
}

function ReportMetric({ label, value }: { label: string; value: number }) {
  return (
    <div className="panel p-4">
      <p className="text-sm font-semibold text-steel">{label}</p>
      <p className="mt-2 text-3xl font-black text-ink">{value}</p>
    </div>
  );
}
